name: Feature request
description: Suggest an enhancement
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
