name: iOS CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode 16.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Show Xcode
        run: xcodebuild -version

      - name: Build (Simulator)
        run: |
          set -eo pipefail
          xcodebuild \
            -project ToDo.xcodeproj \
            -scheme "ToDo" \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            clean build
